version: "3.1"
services:
  redis:
    container_name: redis
    image: redis:6.0.8
    ports:
      - "6379:6379"
    networks:
      - net1

  api:
    container_name: task-queue
    privileged: true
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - FLASK_APP=api/wsgi.py
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - APP_SETTINGS=Development
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
    depends_on:
      - redis
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ".:/code"
    networks:
      - net1

networks:
  net1:
    driver: bridge
